version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install -g @nestjs/cli
      - npm ci

  pre_build:
    commands:
      - echo Setting up environment variables...
      - echo Running Prisma generate...

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Installing production dependencies...
      - npm install --omit=DEV
      - echo Running Prisma generate at Post build...
      - npx prisma generate
      - npm run build
      - npm run start:prod

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'