@Host = localhost:3000
//token gerado pela rota de login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NWJlMzMyNS1iZmE1LTQyYTQtODQ5Zi0zYWNjNjE1YzNiYzIiLCJlbWFpbCI6ImRkZGRkLnMyQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6ImRkZGQiLCJsYXN0TmFtZSI6InRlaXhlaXJhIiwiaW52aXRlQ29kZSI6IlJNYXhZU1JaIiwiaWF0IjoxNzE2MzE3NTUwLCJleHAiOjE3MTY5MjIzNTB9.Zp7PIxL8Qi4KHtW9LXSCTmZ1tXme9iaWWkf8JwdvjF0

###
POST /api/users/ HTTP/1.1
Content-Type: application/json
Host: {{Host}}

{
    "firstName": "Leonardo",
    "lastName": "teixeira",
    "email": "leonardo.s2@gmail.com",
    "password": "Teixeira!@service",
    "inviteSecret": "RMaxYSRZ",
    "ddd": 12,
    "whatsappNumber": 992038461
}

###
PATCH /api/users/7d1211f6-5ca3-4227-aeda-d59b5be59c0a HTTP/1.1
Content-Type: application/json
Host: {{Host}}
Authorization: Bearer {{token}}

{
  "ddd": 11,
  "whatsappNumber": 901728364,
  "isActive": true
}

// FIND ALL
###
GET /api/users?limit=2&page=1 HTTP/1.1
Content-Type: application/json
Host: {{Host}}
Authorization: Bearer {{token}}

// FIND ONE
###
GET /api/users/028601fe-1b97-420b-a559-28f355fb508f HTTP/1.1
Content-Type: application/json
Host: {{Host}}
Authorization: Bearer {{token}}


###
DELETE /api/users/43ed3baa-bb9a-496e-9c8d-c3f285854d1e HTTP/1.1
Content-Type: application/json
Host: {{Host}}
Authorization: Bearer {{token}}


