name: CICD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Generate Deployment Package
        run: zip -r conviceai-userservice.zip . -x 'node_modules/*' -x 'requests/*' -x "test/*" 

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'conviceai-userservice'
          environment_name: 'conviceai-userservice-env'
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: conviceai-userservice.zip